# Generated by Django 6.0.6 on 2026-09-27 22:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('discount_type', models.CharField(choices=[('PERCENT', 'Percent off'), ('AMOUNT', 'Amount off')], max_length=7)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('starts_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('minimum_order', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('once_per_customer', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='orders.coupon')),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
    ]
