# Generated by Django 6.0.6 on 2026-09-27 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='orders.coupon'),
        ),
        migrations.AddField(
            model_name='cart',
            name='coupon_notice',
            field=models.TextField(blank=True),
        ),
    ]
