# Generated by Django 6.0.6 on 2026-09-27 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_coupon_order_coupon_code_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='replaced_coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='orders.coupon'),
        ),
        migrations.AddField(
            model_name='cart',
            name='replaced_coupon_status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
